server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          username: 471240186@qq.com
          password: 471240186dwy
          uri: https://github.com/dwyo/config-repo
          search-paths: respo
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    user: root
    password: 123123

